# Generated by Django 5.0.7 on 2024-07-26 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0002_delete_customer_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('cardID', models.AutoField(primary_key=True, serialize=False)),
                ('billAddress', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prodID', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('prodType', models.CharField(max_length=255)),
                ('prodBrand', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('warehouse', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staffID', models.AutoField(primary_key=True, serialize=False)),
                ('staffName', models.CharField(max_length=255)),
                ('staffAddress', models.CharField(max_length=255)),
                ('salary', models.IntegerField()),
                ('job', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('orderDate', models.DateField()),
                ('status', models.IntegerField()),
                ('cardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.card')),
                ('prodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('shopCartID', models.AutoField(primary_key=True, serialize=False)),
                ('prodID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('accountID', models.AutoField(primary_key=True, serialize=False)),
                ('Cusname', models.CharField(max_length=255)),
                ('cusAddress', models.CharField(max_length=255)),
                ('cardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.card')),
                ('shopCartID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shoppingcart')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('address', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('totalQuantity', models.IntegerField()),
                ('maxQuantity', models.IntegerField()),
                ('staffID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.staff')),
            ],
        ),
    ]
