# Generated by Django 5.0.7 on 2024-07-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_category_alter_product_warehouse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Clothing', 'Clothing'), ('Toys', 'Toys'), ('Electronics', 'Electronics'), ('Home & Kitchen', 'Home & Kitchen'), ('Beauty & Personal Care', 'Beauty & Personal Care'), ('Sports', 'Sports'), ('Health', 'Health'), ('Books & Media', 'Books & Media'), ('Automotive', 'Automotive'), ('Office', 'Office'), ('Pet Supplies', 'Pet Supplies')], max_length=255),
        ),
    ]
