# Generated by Django 5.0.7 on 2024-07-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.CharField(choices=[('123 Main St, Cincinnati, OH', '123 Main St, Cincinnati, OH'), ('5323 Elm St, Spookane, WA', '5323 Elm St, Spookane, WA'), ('69420 Vine St, Poopietown, GA', '69420 Vine St, Poopietown, GA')], max_length=255, primary_key=True, serialize=False),
        ),
    ]
