# Generated by Django 5.0.6 on 2024-07-27 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_warehouse_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='prodCategory',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='prodDescription',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prodType',
            new_name='prodName',
        ),
    ]
