# Generated by Django 5.0.6 on 2024-07-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='shopCartID',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Cusname',
            new_name='cusName',
        ),
        migrations.AddField(
            model_name='card',
            name='cardNumber',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
