# Generated by Django 5.0.6 on 2024-07-27 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_customer_shopcartid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cardNumber',
            field=models.CharField(max_length=16),
        ),
    ]
