# Generated by Django 5.0.6 on 2024-07-30 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_card_cardnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='prodID',
        ),
        migrations.AddField(
            model_name='orders',
            name='accountID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.customer'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('shopCartID', models.AutoField(primary_key=True, serialize=False)),
                ('accountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
            ],
        ),
    ]
